-- require("items.widgets.control_center")
-- require("items.widgets.wechat_and_qq")
require("items.widgets.volume")
-- require("items.widgets.qq")
require("items.widgets.battery")
require("items.widgets.wifi")
require("items.widgets.cpu_and_temp")
require("items.widgets.weather")
require("items.widgets.upcoming_events")
-- require("items.widgets.front_app")
-- require("items.widgets.temperature")
-- require("items.widgets.cpu")
