#!/bin/sh

cat <<EOF | xmenu | sh &

IMG:/home/ecosse/.scripts/xmenu/icons/chrome.png	Google Chrome	google-chrome-stable
IMG:/home/ecosse/.scripts/xmenu/icons/mail.png	Mail	mailspring
IMG:/home/ecosse/.scripts/xmenu/icons/nvim.png	Neovim	kitty --class=Neovim nvim
IMG:/home/ecosse/.scripts/xmenu/icons/folder.png	Files	nautilus

IMG:/home/ecosse/.scripts/xmenu/icons/programming.png	Programming
	IMG:/home/ecosse/.scripts/xmenu/icons/code.png	Visual Studio Code	code
	IMG:/home/ecosse/.scripts/xmenu/icons/eclipse.png	Eclipse	eclipse
	IMG:/home/ecosse/.scripts/xmenu/icons/android-studio.png	Android Studio	android-studio
IMG:/home/ecosse/.scripts/xmenu/icons/video.png	Video
	IMG:/home/ecosse/.scripts/xmenu/icons/screenkey.png	Screen key	screenkey
IMG:/home/ecosse/.scripts/xmenu/icons/chat.png	Messages
	IMG:/home/ecosse/.scripts/xmenu/icons/slack.png	Slack	slack
	IMG:/home/ecosse/.scripts/xmenu/icons/whatsapp.png	Whatsapp	whatsie
	IMG:/home/ecosse/.scripts/xmenu/icons/teams.png	Teams	teams-for-linux
	IMG:/home/ecosse/.scripts/xmenu/icons/skype.png	Skype	skype
	IMG:/home/ecosse/.scripts/xmenu/icons/teamspeak.png	TeamSpeak 3	teamspeak3
IMG:/home/ecosse/.scripts/xmenu/icons/tools.png	Tools
	IMG:/home/ecosse/.scripts/xmenu/icons/timeshift.png	Backup	kitty sudo timeshift-gtk
	IMG:/home/ecosse/.scripts/xmenu/icons/system-monitor.png	System Monitor	kitty gotop
	IMG:/home/ecosse/.scripts/xmenu/icons/ncdu.png	Clean Up	kitty ncdu
EOF
