#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down

function get_brightness {
    xbacklight -get | cut -d. -f1
}

function send_notification {
    DIR=`dirname "$0"`
    brightness=`get_brightness`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
#bar=$(seq -s "─" $(($volume/5)) | sed 's/[0-9]//g')
if [ "$brightness" = "0" ]; then
        icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
$DIR/notify-send-volume.sh "$brightness""      " -i "$icon_name" -t 2000 -h int:value:"$brightness" -h string:synchronous:"─" --replace=555
    else
	if [  "$brightness" -lt "10" ]; then
	     icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
$DIR/notify-send-volume.sh "$brightness""     " -i "$icon_name" --replace=555 -t 2000
    else
        if [ "$brightness" -lt "30" ]; then
            icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
        else
            if [ "$brightness" -lt "70" ]; then
                icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
            else
                icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
            fi
        fi
    fi
fi
bar=$(seq -s "─" $(($brightness/5)) | sed 's/[0-9]//g')
# Send the notification
$DIR/notify-send-volume.sh "$brightness""     ""$bar" -i "$icon_name" -t 2000 -h int:value:"$brightness" -h string:synchronous:"$bar" --replace=555

}

case $1 in
    up)
  xbacklight -inc 10
	send_notification
	;;
    down)
  xbacklight -dec 10
	send_notification
esac
